/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as AuthenticatedViveirosRouteImport } from './routes/_authenticated.viveiros'
import { Route as AuthenticatedValesRouteImport } from './routes/_authenticated.vales'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated.produtos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCaixaRouteImport } from './routes/_authenticated.caixa'
import { Route as AuthenticatedBiometriasRouteImport } from './routes/_authenticated.biometrias'
import { Route as ApiPublicRelatorioTokenRouteImport } from './routes/api/public/relatorio.$token'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedViveirosRoute = AuthenticatedViveirosRouteImport.update({
  id: '/viveiros',
  path: '/viveiros',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedValesRoute = AuthenticatedValesRouteImport.update({
  id: '/vales',
  path: '/vales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCaixaRoute = AuthenticatedCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBiometriasRoute = AuthenticatedBiometriasRouteImport.update({
  id: '/biometrias',
  path: '/biometrias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicRelatorioTokenRoute = ApiPublicRelatorioTokenRouteImport.update({
  id: '/api/public/relatorio/$token',
  path: '/api/public/relatorio/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/biometrias': typeof AuthenticatedBiometriasRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vales': typeof AuthenticatedValesRoute
  '/viveiros': typeof AuthenticatedViveirosRoute
  '/r/$token': typeof RTokenRoute
  '/api/public/relatorio/$token': typeof ApiPublicRelatorioTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/biometrias': typeof AuthenticatedBiometriasRoute
  '/caixa': typeof AuthenticatedCaixaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vales': typeof AuthenticatedValesRoute
  '/viveiros': typeof AuthenticatedViveirosRoute
  '/r/$token': typeof RTokenRoute
  '/api/public/relatorio/$token': typeof ApiPublicRelatorioTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/biometrias': typeof AuthenticatedBiometriasRoute
  '/_authenticated/caixa': typeof AuthenticatedCaixaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/vales': typeof AuthenticatedValesRoute
  '/_authenticated/viveiros': typeof AuthenticatedViveirosRoute
  '/r/$token': typeof RTokenRoute
  '/api/public/relatorio/$token': typeof ApiPublicRelatorioTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/biometrias'
    | '/caixa'
    | '/dashboard'
    | '/produtos'
    | '/relatorios'
    | '/vales'
    | '/viveiros'
    | '/r/$token'
    | '/api/public/relatorio/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/biometrias'
    | '/caixa'
    | '/dashboard'
    | '/produtos'
    | '/relatorios'
    | '/vales'
    | '/viveiros'
    | '/r/$token'
    | '/api/public/relatorio/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/biometrias'
    | '/_authenticated/caixa'
    | '/_authenticated/dashboard'
    | '/_authenticated/produtos'
    | '/_authenticated/relatorios'
    | '/_authenticated/vales'
    | '/_authenticated/viveiros'
    | '/r/$token'
    | '/api/public/relatorio/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicRelatorioTokenRoute: typeof ApiPublicRelatorioTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/viveiros': {
      id: '/_authenticated/viveiros'
      path: '/viveiros'
      fullPath: '/viveiros'
      preLoaderRoute: typeof AuthenticatedViveirosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vales': {
      id: '/_authenticated/vales'
      path: '/vales'
      fullPath: '/vales'
      preLoaderRoute: typeof AuthenticatedValesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/caixa': {
      id: '/_authenticated/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof AuthenticatedCaixaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/biometrias': {
      id: '/_authenticated/biometrias'
      path: '/biometrias'
      fullPath: '/biometrias'
      preLoaderRoute: typeof AuthenticatedBiometriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/relatorio/$token': {
      id: '/api/public/relatorio/$token'
      path: '/api/public/relatorio/$token'
      fullPath: '/api/public/relatorio/$token'
      preLoaderRoute: typeof ApiPublicRelatorioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBiometriasRoute: typeof AuthenticatedBiometriasRoute
  AuthenticatedCaixaRoute: typeof AuthenticatedCaixaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedValesRoute: typeof AuthenticatedValesRoute
  AuthenticatedViveirosRoute: typeof AuthenticatedViveirosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBiometriasRoute: AuthenticatedBiometriasRoute,
  AuthenticatedCaixaRoute: AuthenticatedCaixaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedValesRoute: AuthenticatedValesRoute,
  AuthenticatedViveirosRoute: AuthenticatedViveirosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicRelatorioTokenRoute: ApiPublicRelatorioTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
