// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aekuxajnyaewfxffihen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFla3V4YWpueWFld2Z4ZmZpaGVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAxNzM2MjQsImV4cCI6MjA5NTc0OTYyNH0.gg_4Fes1CbO-gdeH9wI8PwCbYrXxcQqWFuE08byY4Fc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});